# -*- coding: utf-8 -*-
"""Notebook_02_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/crazyandiee/ride-sharing-demand-forecasting/blob/main/Notebooks/Notebook_02_EDA.ipynb
"""

!mkdir -p data/raw data/processed data/merged notebooks

# Upload taxi + weather csv
from google.colab import files
files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load merged dataset
df = pd.read_csv("/content/data/merged/nyc_demand_weather_merged.csv")

# Convert pickup_hour back to datetime
df['pickup_hour'] = pd.to_datetime(df['pickup_hour'])

# Define NYC Taxi theme
nyc_yellow = "#F3C200"
nyc_black = "#000000"

plt.style.use('ggplot')

plt.figure(figsize=(16,5))
plt.plot(df['pickup_hour'], df['trip_count'], color=nyc_black, linewidth=1.8)
plt.title("NYC Hourly Taxi Demand - Jan 2023", fontsize=16, color=nyc_black)
plt.xlabel("Date", fontsize=12, color=nyc_black)
plt.ylabel("Trips per Hour", fontsize=12, color=nyc_black)
plt.grid(alpha=0.3)
plt.gca().set_facecolor(nyc_yellow + "20") # very light yellow
plt.show()

"""The demand for taxis shows a strong daily repeating pattern.
Demand drops during late night/early morning (2 AM–6 AM) and peaks in late afternoon/evening (4 PM–7 PM).
This consistent periodic behavior indicates strong seasonality, making the problem suitable for time-series forecasting.


Taxi fleet/staffing can be optimized by increasing availability during peak hours.
"""

df['hour'] = df['pickup_hour'].dt.hour
avg_hourly = df.groupby('hour')['trip_count'].mean()

plt.figure(figsize=(10,5))
avg_hourly.plot(kind='bar', color=nyc_yellow, edgecolor=nyc_black)
plt.title("Avg Demand per Hour of Day", fontsize=16, color=nyc_black)
plt.xlabel("Hour of Day", fontsize=12)
plt.ylabel("Avg Trips", fontsize=12)
plt.show()

"""Hour-of-day has a consistent effect on taxi demand.
The lowest demand occurs around 5 AM, and the highest around 5 PM due to office commute and evening travel.


Dynamic pricing + more cabs during commute hours boosts revenue.
"""

corr = df[['trip_count','tmpf','relh','p01i','sknt']].corr()

plt.figure(figsize=(8,5))
plt.imshow(corr, cmap="inferno")
plt.title("Correlation: Weather vs Taxi Demand", color=nyc_black)
plt.xticks(range(len(corr)), corr.columns, rotation=45, ha='right')
plt.yticks(range(len(corr)), corr.columns)
plt.colorbar()
plt.show()

"""Weather factors show weak but noticeable relationships with demand.
Humidity (relh) shows a slight positive correlation → bad weather days increase taxi use.
Temperature does not correlate strongly due to the cool winter month (Jan only).


Weather influences rider decisions — integrating weather in prediction can improve forecasting accuracy.
"""

plt.scatter(df['tmpf'], df['trip_count'], color=nyc_black, alpha=0.5)
plt.title("Temperature vs Taxi Demand")
plt.xlabel("Temperature (°F)")
plt.ylabel("Trips / Hour")
plt.show()

"""Demand tends to increase at colder temperatures (below 45°F).
Riders choose taxis more when weather is uncomfortable for walking.


Predictive pricing/availability should consider temperature drops.
"""

