# -*- coding: utf-8 -*-
"""Notebook_1_Data_Preprocessing_(Taxi_+_Weather).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXOKcZOfqE3rAU_0QYnqcIz33lRLbAg3
"""

!mkdir -p data/raw data/processed data/merged

from google.colab import files

uploaded = files.upload(

) # select both raw CSV files

import shutil
shutil.move("NYC TLC Trip Record.csv", "data/raw/NYC TLC Trip Record.csv")
shutil.move("EWR.csv", "data/raw/EWR.csv")

import pandas as pd
import numpy as np

# File paths (adjust if needed)
taxi_path = "/content/data/raw/NYC TLC Trip Record.csv"
weather_path = "/content/data/raw/EWR.csv"

taxi = pd.read_csv(taxi_path)
weather = pd.read_csv(weather_path)

taxi = pd.read_csv(taxi_path, dtype=str, low_memory=False)
weather = pd.read_csv(weather_path, dtype=str, low_memory=False)

# Fix datetime columns in taxi dataset
taxi['lpep_pickup_datetime'] = pd.to_datetime(taxi['lpep_pickup_datetime'], errors='coerce')
taxi['lpep_dropoff_datetime'] = pd.to_datetime(taxi['lpep_dropoff_datetime'], errors='coerce')

# Fix datetime in weather dataset
weather['valid'] = pd.to_datetime(weather['valid'], errors='coerce')

# Quick preview
taxi.head(), weather.head()

# Create hourly pickup bucket
taxi['pickup_hour'] = taxi['lpep_pickup_datetime'].dt.floor('h')

# Drop rows without valid hour
taxi = taxi.dropna(subset=['pickup_hour'])

# Group to get number of trips per hour
hourly_taxi = (
    taxi.groupby('pickup_hour')
        .size()
        .reset_index(name='trip_count')
)

hourly_taxi.head(), hourly_taxi.tail()

# List of numeric weather fields we need
numeric_cols = ['tmpf', 'dwpf', 'relh', 'sknt', 'mslp', 'p01i']

# Convert to numeric types
for col in numeric_cols:
    weather[col] = pd.to_numeric(weather[col], errors='coerce')

# Round weather timestamps to the nearest hour
weather['weather_hour'] = weather['valid'].dt.round('h')

# Remove rows without weather hour
weather = weather.dropna(subset=['weather_hour'])

# Aggregate weather (avg values per hour)
weather_hourly = (
    weather.groupby('weather_hour')
           .agg({
               'tmpf':'mean',  # Temperature (°F)
               'dwpf':'mean',  # Dew point
               'relh':'mean',  # Humidity %
               'sknt':'mean',  # Wind speed (knots)
               'mslp':'mean',  # Pressure (mb)
               'p01i':'sum'    # Hourly precipitation (inches)
           })
           .reset_index()
)
weather_hourly.head()

merged = pd.merge(
    hourly_taxi,
    weather_hourly,
    left_on='pickup_hour',
    right_on='weather_hour',
    how='inner'
)

merged.head(), merged.shape

# Drop duplicate timestamp column
merged = merged.drop(columns=['weather_hour'])

# Save clean version
merged.to_csv("data/merged/nyc_demand_weather_merged.csv", index=False)

merged.head(), merged.shape

# Create folders if not present
import os
os.makedirs("/content/data/processed", exist_ok=True)
os.makedirs("/content/data/merged", exist_ok=True)

hourly_taxi.to_csv("/content/data/processed/nyc_hourly_demand.csv", index=False)
weather_hourly.to_csv("/content/data/processed/nyc_hourly_weather.csv", index=False)
merged.to_csv("/content/data/merged/nyc_demand_weather_merged.csv", index=False)

merged.head()
merged.shape